---
services:
  db:
    env_file:
      - path: ./conf/local.twlight.env
        required: true
      - path: .env
        required: false
  twlight:
    image: quay.io/wikipedialibrary/twlight:local
    # Local environment should mount things from the code directory
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - path: ./conf/local.twlight.env
        required: true
      - path: .env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web:
    volumes:
      - type: bind
        source: ./conf/local.nginx.conf
        target: /etc/nginx/conf.d/default.conf
